package object;

public class Book {
    String ISBN;

    public Book(String s) {
        this.ISBN = s;
    }

    public String getISBN() { 
        return ISBN;
    }

//  Note: If we override equals(), you must override hashCode() as well.
    public boolean equals(Object obj) {
        if (obj instanceof Book)
            return ISBN.equals(((Book) obj).getISBN());
        else
            return false;
    }

    /*
    * The hashCode() Method
    * The value returned by hashCode() is the object's hash code,
    * which is an integer value generated by a hashing algorithm.
    *
    * By definition, if two objects are equal, their hash code must also be equal.
    * If we override the equals() method, we change the way two objects are equated
    * and Object's implementation of hashCode() is no longer valid.
    *
    * Therefore, if we override the equals() method, we must also override the hashCode() method as well.
    * */

    void printClassName(Object obj) {
        System.out.println("The object's" + " class is " +
                obj.getClass().getSimpleName());
    }

    public static void main(String[] args){
        Book firstBook  = new Book("0201914670");
        Book secondBook = new Book("0201914670");
        if (firstBook.equals(secondBook)) {
            System.out.println("objects are equal");
        } else {
            System.out.println("objects are not equal");
        }

        firstBook.printClassName(secondBook);
    }

}